### ISSUE TITLE
#scenario-overview will not render on my html page.

### ISSUE THREAD

**Issue by nodeJerry** [dutchiexl/BehatHtmlFormatterPlugin#117]
Hi
Can anyone tell me why #scenario-overview will not display on my report.
Please 
I can see feature_overview (this is displayed)

I am using configuration
```
    extensions:
       emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
          name: html
          renderer: Twig,Behat2
          file_name: index
          print_args: true
          print_outp: true
          loop_break: true
```
