### ISSUE TITLE
In ExtensionManager.php line 194:     `emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension` extension file or class  could not be located.

### ISSUE THREAD

**Issue by samiullah** [dutchiexl/BehatHtmlFormatterPlugin#129]
Getting following error
```
In ExtensionManager.php line 194:


  `emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension` extension file or class
 could not be located.
```

Following is my behat.yml
```

default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - emuse\BehatHTMLFormatter\Context\ScreenshotContext:
            screenshotDir: report/html/behat/assets/screenshots
  formatters:
    html:
      output_path: %paths.base%/build/html/behat
  extensions:
    emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
      name: html
      renderer: Twig,Behat2
      file_name: index
      print_args: true
      print_outp: true

    Behat\MinkExtension:
        browser_name: 'chrome'
        goutte: ~
        javascript_session: selenium2
        selenium2:
          wd_host: http://127.0.0.1:4444/wd/hub
          #capabilities: { "version": "*", 'chrome': {'switches':['--start-maximized']},"extra_capabilities": {"w3c":"false"}}
          capabilities:
            chrome:
              switches:
                - "--start-maximized"
            extra_capabilities:
              goog:chromeOptions:
                w3c: false

        base_url: 'http://localhost/corporate/docroot/'
    Drupal\DrupalExtension:
      blackbox: ~
      api_driver: drupal
      drupal:
        drupal_root: C:\xampp\htdocs\corporate\docroot
    Bex\Behat\ScreenshotExtension:
      screenshot_taking_mode: failed_scenarios
      image_drivers:
        local:
          screenshot_directory: "%paths.base%/media/failed_screenshots"
```
Php version 7.4
I am running on windows 10 XAMPP
