### ISSUE TITLE
Passing null to parameter #1 ($filename) of type string is deprecated in emuse/behat-html-formatter/src/Classes/Scenario.php

### ISSUE THREAD

**Issue by MuthuvelBalu** [dutchiexl/BehatHtmlFormatterPlugin#130]
Getting a php deprecation error while generate the html report.
PHP Deprecated:  file_exists(): Passing null to parameter #1 ($filename) of type string is deprecated in /vendor/emuse/behat-html-formatter/src/Classes/Scenario.php on line 205

**Comment by dgtlmoon** [comment]
@MuthuvelBalu since you dont say which PHP version you are running, I'm going to assume you are talking about PHP8 (not 5, or 7)

I found the "fix" was a missing context config in `behat.yml`

```
  suites:
    default:
      contexts:
        - emuse\BehatHTMLFormatter\Context\ScreenshotContext:
             screenshotDir: /var/www/site/tests-metadata/acceptance/html/assets/screenshots
```
