### ISSUE TITLE
I18N for HTML-Output

### ISSUE THREAD

**Issue by ScreamingDev** [dutchiexl/BehatHtmlFormatterPlugin#31]
As I set my language to "de"

```
default:
  translation:
    locale: de
  extensions:
    Behat\MinkExtension:
      sessions:
        default:
          goutte: ~
    emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
      name: html
      renderer: Twig
  formatters:
    html:
      output_path:
        %paths.base%/var/behat
  autoload:
    '': %paths.base%/tests/features/bootstrap
  suites:
    wordpress:
      paths: [ %paths.base%/tests/features ]
      contexts: [ WordPressContext ]
```

the behat output with other formatter is German (de). But the words "Feature", "Scenario" are still english in the HTML-Output. As there is still no HTML-Ouput for Behat3 and yours look very good, please fix this :)

Cheers!
