### ISSUE TITLE
Getting an error message related to configuration made in yml file under Emuse externsion

### ISSUE THREAD

**Issue by maheshmanjunath01** [dutchiexl/BehatHtmlFormatterPlugin#41]
![image](https://cloud.githubusercontent.com/assets/5356751/9272436/438886d2-427a-11e5-8b5b-28d955108ff8.png)

Got above error : 
MY YML configuration 
 emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
        name: html
        renderer: Twig
        file_name: index
        print_args: true
        print_outp: true
        loop_break: true

Could you please let me know if I had done some configuration mistake.

**Comment by fonsecas72** [comment]
Can you paste your yml config between ``` chars? please

**Comment by maheshmanjunath01** [comment]
default:
    formatters:
        html:
            output_path: %paths.base%/reports
            screenshots_path: %paths.base%/reports/screenshots
        pretty:
            output_path: %paths.base%/pretty.txt

```
suites:
  dev:
    contexts:
      - FeatureContext:
          parameters:
            base_url: 'https://xxxxx.org'
            ddfile_path: %paths.base%/dd
            credentials:
              xxx:
                Sudsfdsf:
                  username: "XXXXXX"
                  password: ",,,,,,"                      

extensions:
  Behat\MinkExtension:
    base_url: 'https://xxxxx.org'
    default_session: 'selenium2'
    javascript_session:  'selenium2'
    browser_name: firefox
    selenium2: ~
    goutte: ~   
  emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
    name: html
    renderer: Twig
    file_name: index
```
