### ISSUE TITLE
Not all Features are in report

### ISSUE THREAD

**Issue by Gordiievskyi** [dutchiexl/BehatHtmlFormatterPlugin#43]
Hi guys,

Behat 3.0.15
Php unit 4.8.3
Tests executes from bamboo unix on slave Windows 7.
After nightly build I have report with not all feature in it.
In report at the bottom I do not see thouse circlus like you have on screen shots but only the text:

3 features failed of 14 features. 4 scenarios failed of 36 scenarios,35 steps failed of 1479 and then below description for thouse 6 features I see in the body.If you need I can send tar file. Also attached the screenshot and my yml file below.

Clicks on buttons all passed failed do nothing.
![log](https://cloud.githubusercontent.com/assets/10296676/9907922/06290b4c-5c9a-11e5-9734-de6d7431bff6.jpg)

```
default:
    autoload:
         '': %paths.base%/features/bootstrap
    suites:
        test:
            paths:
                - %paths.base%/features
            contexts:
                - HorseProfileContext
            filters:
                tags: @fakeData,@realData,@brokenTest,@disabledTest
    formatters:
        html:
          output_path: %paths.base%/build/html/behat

    extensions:
        emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
            name: html
            renderer: Twig,Behat2
            file_name: Index
            print_args: true
            print_outp: true
            loop_break: true
```

Aditional remark: When I run one feature on my local pc(php storm added reporter through composer in storm) report is ok.
