### ISSUE TITLE
console output disappears

### ISSUE THREAD

**Issue by tanguybernard** [dutchiexl/BehatHtmlFormatterPlugin#56]
Hello,
When I'm using some basic configuration:

```
default:

extensions:
     emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
          name: html
          renderer: Twig,Behat2
          file_name: Index
          print_args: true
          print_outp: true
          loop_break: true

formatters:
    html:
      output_path: %paths.base%/build/html/behat
```

The console output disappears, but html generation works fine!

Did I miss something ?

**Comment by karina-may** [comment]
Add `pretty:` under formatters, then it still prints the pretty output to console:

```
default:
  formatters:
    pretty:
    html:
      output_path: %paths.base%/build/behat
```
