### ISSUE TITLE
incompatibility with chrome-mink-driver

### ISSUE THREAD

**Issue by drzraf** [dutchiexl/BehatHtmlFormatterPlugin#95]
See this issue: https://gitlab.com/DMore/chrome-mink-driver/issues/36
With config like:
```
  formatters:
    html:
      output_path: %paths.base%/tests/coverage
  extensions:
    DMore\ChromeExtension\Behat\ServiceContainer\ChromeExtension: ~
    Behat\MinkExtension:
      browser_name: chrome
    emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
      name: html
      # don't generate Behat2
      renderer: Twig
      file_name: index
      print_args: true
      print_outp: true
      loop_break: true
```
I'm having quite consistent browser errors
Especially after switching chrome-mink-driver from 2.2.0 to 2.3.0
Maybe related to this trace (see above mentioned issue)
`Catchable Fatal Error: Argument 1 passed to emuse\BehatHTMLFormatter\Formatter\BehatHTMLFormatter::onAfterExercise() must be an instance of Behat\Testwork\EventDispatcher\Event\AfterExerciseCompleted, instance of Behat\Testwork\EventDispatcher\Event\AfterExerciseAborted given in tests/vendor/emuse/behat-html-formatter/src/Formatter/BehatHTMLFormatter.php line 395`
Even with other version dmore-chrome* extensions version, I can hit different failures (mostly Chrome timeout) when BehatHtmlFormatterPlugin is enabled.
